version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "ap-northeast-1"
    ACCOUNT_ID: "963220189927"
    ECR_REPO_PHP: "ecr-php-yoshiike-20251019"
    ECR_REPO_PHP_Apache: "ecr-php-apache-yoshiike-20251019"
    CONTAINER_NAME: "php"

phases:

  pre_build:
    commands:
      - echo "Login to ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build:
    commands:
      - echo Build Docker image for php...
      - docker build \
          --build-arg ACCOUNT_ID=$ACCOUNT_ID \
          --build-arg REGION=$AWS_DEFAULT_REGION \
          --build-arg ECR_REPO_PHP_Apache=$ECR_REPO_PHP_Apache \
          -t $ECR_REPO_PHP:latest ./app      
      - docker tag $ECR_REPO_PHP:latest $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO_PHP:latest

  post_build:
    commands:
      - echo "start to push"
      - docker push $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO_PHP:latest
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO_PHP:latest > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json

